[package]
name = "sauw"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.4.1"
bevy = { version = "0.17.3" }
bevy_console = "0.16.0"
bevy_winit = "0.17.3"
clap = "4.5.54"
image = "0.25.9"
noise = "0.9.0"
rand = "0.9.2"
winit = "0.30.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
